name: Check
on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  build:
    name: Build on golang ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version:
          - "1.25"
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Get dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v -o /dev/null ./cmd/gt

